### ISSUE TITLE
Modlist can not be installed

### ISSUE THREAD

**Issue by PieJey** [JanuarySnow/Curseadelica#1]
The modlist cannot be installed because Wabbajack wants to download enbseries_v0473. However, this is no longer available for download.
![Curseadelica-Error](https://user-images.githubusercontent.com/112122595/186752694-d434f79a-1a15-4c5c-ba12-7176f43ba4db.png)

**Comment by KaiPrince** [comment]
I was asking in the Wabbajack discord if there's a way to use a different version. They said no, but gave me this link to exactly the file needed: https://build.wabbajack.org/authored_files/direct_link/enbseries_skyrimse_v0473.zip_4b8db8b2-7fc4-4fbd-99ae-3ce78a1d7a75

**Comment by KaiPrince** [comment]
Also I found this handy guide to downgrading Skyrim to the before Anniversary Edition version: https://www.reddit.com/r/skyrim/comments/qtifsd/howto_setup_skyrim_special_edition_1597_yourself/

**Comment by JanuarySnow** [comment]
Now updated, and installable
